### ISSUE TITLE
Compiled with Problems error

### ISSUE THREAD

**Issue by pdxjoe** [aws-samples/amazon-ivs-clip-manifest#13]
I'm not an expert, so pardon my inexperience.  

First off, this project is awesome!  I have it running and will put it to good use for a medical conference we will stream live in 2 weeks.  This project will allow us to immediately provide vod clips. It's going to be crazy popular.  

When I load the web front end, I receive the following error.  This is running on my Mac, following the instructions to the letter.  during the NPM install, I did receive notices about updating packages.  I did not perform these updates.  

<img width="1039" alt="Screenshot 2023-04-02 at 8 20 17 PM" src="https://user-images.githubusercontent.com/2320788/229405375-f71d04d7-ad73-477f-a383-82f223f8c59a.png">

I do want to figure out how to expose the clip created url on the web UI.  Right now, the clip is an icon, but in order to gain access to the trimmed .m3u8 you have to browse the directory structure.  

I will also be looking into the API, my guess is that I might have enough skillset to make something... but the web UI is close to perfect for my needs.

**Comment by osmarbento-AWS** [comment]
Hi @pdxjoe thank you for your comments. The url is been retrieved from the api in the folder 'manifest-clip-ui/src/components/apis' Then this is passed to the player. This error mean that it might be an invalid source, and the player is not ready.  Anyways this should be treated and handled, can you detail what is the source that you are trying to play? also please check if the videojs was properly installed.

**Comment by pdxjoe** [comment]
This was a while ago and I can't recall how we resolved the issue.  Since then, we have used the IVS Manifest Clipping code at several events with success.  I'm going to ask our developer if he can share some of the enhancements.  

One issue we quickly hit was the limitation of S3 objects that can be returned.  We resolved this by updating the UI with selections for Channel ID, Month, and Day.
